### ISSUE TITLE
成功运行过，但后面就无法运行了，电脑重置之后依然无法解决

### ISSUE THREAD

**Issue by irainerc** [bennyxguo/hexo-theme-obsidian#153]
$ hexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 117 ms
ERROR TypeError: B:\Website\Hexo\Rainerc\themes\obsidian\layout\post.ejs:4
    2|     <%- partial("_partial/post/header")%>
    3|     <div class="section">
 >> 4|         <%- partial("_partial/post/article")%>
    5|     </div>
    6| </div>

B:\Website\Hexo\Rainerc\themes\obsidian\layout\_partial\post\article.ejs:22
    20|             <h3 class="post-title animated fadeInDown"><%- link_to(page.path, page.title || "Untitled", {class: ""}) %>
    21|             </h3>
 >> 22|             <% if (theme.symbols_count_time.enable) {%>
    23|             <p class="post-count animated fadeInDown">
    24|                 <% if (theme.symbols_count_time.wordCount) { %>
    25|                 <span>

Cannot read property 'enable' of undefined
    at eval (B:\Website\Hexo\Rainerc\themes\obsidian\layout\_partial\post\article.ejs:39:37)
    at article (B:\Website\Hexo\Rainerc\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (B:\Website\Hexo\Rainerc\themes\obsidian\layout\post.ejs:15:17)
    at post (B:\Website\Hexo\Rainerc\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\theme\view.js:39:17)
    at B:\Website\Hexo\Rainerc\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (B:\Website\Hexo\Rainerc\node_modules\bluebird\js\release\util.js:16:23)
    at B:\Website\Hexo\Rainerc\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:462:10)
    at resume_ (internal/streams/readable.js:958:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  path: 'B:\\Website\\Hexo\\Rainerc\\themes\\obsidian\\layout\\post.ejs'
}
ERROR TypeError: B:\Website\Hexo\Rainerc\themes\obsidian\layout\archive.ejs:10
    8|                 <div class="content animated fadeIn">
    9|                     <div class="set">
 >> 10|                         <h1 style="text-align: center"><%= theme.page_titles.archives || __("Archived") %></h1>
    11|                         <p style="text-align: center">「 <%= site.posts.length %> 」</p>
    12|                         <ul class="timeline timeline-centered">
    13|                             <% var posts = site.posts.sort('date', 'desc'); %>

Cannot read property 'archives' of undefined
    at eval (B:\Website\Hexo\Rainerc\themes\obsidian\layout\archive.ejs:12:44)
    at archive (B:\Website\Hexo\Rainerc\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\theme\view.js:39:17)
    at B:\Website\Hexo\Rainerc\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (B:\Website\Hexo\Rainerc\node_modules\bluebird\js\release\util.js:16:23)
    at B:\Website\Hexo\Rainerc\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:462:10)
    at resume_ (internal/streams/readable.js:958:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  path: 'B:\\Website\\Hexo\\Rainerc\\themes\\obsidian\\layout\\archive.ejs'
}
ERROR TypeError: B:\Website\Hexo\Rainerc\themes\obsidian\layout\archive.ejs:10
    8|                 <div class="content animated fadeIn">
    9|                     <div class="set">
 >> 10|                         <h1 style="text-align: center"><%= theme.page_titles.archives || __("Archived") %></h1>
    11|                         <p style="text-align: center">「 <%= site.posts.length %> 」</p>
    12|                         <ul class="timeline timeline-centered">
    13|                             <% var posts = site.posts.sort('date', 'desc'); %>

Cannot read property 'archives' of undefined
    at eval (B:\Website\Hexo\Rainerc\themes\obsidian\layout\archive.ejs:12:44)
    at archive (B:\Website\Hexo\Rainerc\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\theme\view.js:39:17)
    at B:\Website\Hexo\Rainerc\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (B:\Website\Hexo\Rainerc\node_modules\bluebird\js\release\util.js:16:23)
    at B:\Website\Hexo\Rainerc\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:462:10)
    at resume_ (internal/streams/readable.js:958:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  path: 'B:\\Website\\Hexo\\Rainerc\\themes\\obsidian\\layout\\archive.ejs'
}
ERROR TypeError: B:\Website\Hexo\Rainerc\themes\obsidian\layout\archive.ejs:10
    8|                 <div class="content animated fadeIn">
    9|                     <div class="set">
 >> 10|                         <h1 style="text-align: center"><%= theme.page_titles.archives || __("Archived") %></h1>
    11|                         <p style="text-align: center">「 <%= site.posts.length %> 」</p>
    12|                         <ul class="timeline timeline-centered">
    13|                             <% var posts = site.posts.sort('date', 'desc'); %>

Cannot read property 'archives' of undefined
    at eval (B:\Website\Hexo\Rainerc\themes\obsidian\layout\archive.ejs:12:44)
    at archive (B:\Website\Hexo\Rainerc\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\theme\view.js:39:17)
    at B:\Website\Hexo\Rainerc\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (B:\Website\Hexo\Rainerc\node_modules\bluebird\js\release\util.js:16:23)
    at B:\Website\Hexo\Rainerc\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:462:10)
    at resume_ (internal/streams/readable.js:958:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  path: 'B:\\Website\\Hexo\\Rainerc\\themes\\obsidian\\layout\\archive.ejs'
}
ERROR TypeError: B:\Website\Hexo\Rainerc\themes\obsidian\layout\index.ejs:3
    1| <%- partial("_partial/menu", null, {cache: true}) %>
    2| <div id="container">
 >> 3|     <%- partial("_partial/screen", null, {cache: false}) %>
    4|     <div id="primary">
    5|         <%- partial('_partial/list', {start: 1}) %>
    6|     </div>

B:\Website\Hexo\Rainerc\themes\obsidian\layout\_partial\screen.ejs:57
    55|         <h3 class="post-title animated fadeInDown">
    56|             <%- link_to(first.path, first.title || config.title, {class: "posttitle"}) %></h3>
 >> 57|         <% if (theme.symbols_count_time.enable) {%>
    58|         <p class="post-count animated fadeInDown">
    59|             <% if (theme.symbols_count_time.wordCount) { %>
    60|             <span>

Cannot read property 'enable' of undefined
    at eval (B:\Website\Hexo\Rainerc\themes\obsidian\layout\_partial\screen.ejs:72:37)
    at screen (B:\Website\Hexo\Rainerc\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (B:\Website\Hexo\Rainerc\themes\obsidian\layout\index.ejs:13:17)
    at index (B:\Website\Hexo\Rainerc\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\theme\view.js:39:17)
    at B:\Website\Hexo\Rainerc\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (B:\Website\Hexo\Rainerc\node_modules\bluebird\js\release\util.js:16:23)
    at B:\Website\Hexo\Rainerc\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (B:\Website\Hexo\Rainerc\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:462:10)
    at resume_ (internal/streams/readable.js:958:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  path: 'B:\\Website\\Hexo\\Rainerc\\themes\\obsidian\\layout\\index.ejs'
}
INFO  0 files generated in 16 ms

**Comment by bennyxguo** [comment]
这个很有可能是配置无法读取到的问题，检查两个问题。

1. 有没有按照[这里](https://aurora.tridiamond.tech/zh/guide/getting-started.html#%E6%AD%A5%E9%AA%A4-2-%E7%94%9F%E6%88%90%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE)复制了 aurora 的配置?
```shell
cp -rf ./node_modules/hexo-theme-aurora/_config.yml ./_config.aurora.yml
```

2. `_config.yml` 里面的 `theme` 是否设置为 `aurora`?

**Comment by kcn3388** [comment]
@irainerc @GodD6366 请仔细阅读安装指南，并通过修改配置模板的方式构建配置文件
