### ISSUE TITLE
运行hexo g时报错

### ISSUE THREAD

**Issue by Pleasecallmeboss** [bennyxguo/hexo-theme-obsidian#159]
E:\Projects\Blog\blog>hexo clean && hexo g
INFO  Validating config
INFO  Deleted database.
INFO  Deleted public folder.
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 258 ms
ERROR TypeError: E:\Projects\Blog\blog\themes\obsidian\layout\archive.ejs:10
    8|                 <div class="content animated fadeIn">
    9|                     <div class="set">
 >> 10|                         <h1 style="text-align: center"><%= theme.page_titles.archives || __("Archived") %></h1>
    11|                         <p style="text-align: center">「 <%= site.posts.length %> 」</p>
    12|                         <ul class="timeline timeline-centered">
    13|                             <% var posts = site.posts.sort('date', 'desc'); %>

Cannot read property 'archives' of undefined
    at eval (E:\Projects\Blog\blog\themes\obsidian\layout\archive.ejs:12:44)
    at archive (E:\Projects\Blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Projects\Blog\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\Projects\Blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Projects\Blog\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\Projects\Blog\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: 'E:\\Projects\\Blog\\blog\\themes\\obsidian\\layout\\archive.ejs'
}
ERROR TypeError: E:\Projects\Blog\blog\themes\obsidian\layout\post.ejs:4
    2|     <%- partial("_partial/post/header")%>
    3|     <div class="section">
 >> 4|         <%- partial("_partial/post/article")%>
    5|     </div>
    6| </div>

E:\Projects\Blog\blog\themes\obsidian\layout\_partial\post\article.ejs:22
    20|             <h3 class="post-title animated fadeInDown"><%- link_to(page.path, page.title || "Untitled", {class: ""}) %>
    21|             </h3>
 >> 22|             <% if (theme.symbols_count_time.enable) {%>
    23|             <p class="post-count animated fadeInDown">
    24|                 <% if (theme.symbols_count_time.wordCount) { %>
    25|                 <span>

Cannot read property 'enable' of undefined
    at eval (E:\Projects\Blog\blog\themes\obsidian\layout\_partial\post\article.ejs:39:37)
    at article (E:\Projects\Blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (E:\Projects\Blog\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\Projects\Blog\blog\themes\obsidian\layout\post.ejs:15:17)
    at post (E:\Projects\Blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Projects\Blog\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\Projects\Blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Projects\Blog\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\Projects\Blog\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: 'E:\\Projects\\Blog\\blog\\themes\\obsidian\\layout\\post.ejs'
}
ERROR TypeError: E:\Projects\Blog\blog\themes\obsidian\layout\post.ejs:4
    2|     <%- partial("_partial/post/header")%>
    3|     <div class="section">
 >> 4|         <%- partial("_partial/post/article")%>
    5|     </div>
    6| </div>

E:\Projects\Blog\blog\themes\obsidian\layout\_partial\post\article.ejs:22
    20|             <h3 class="post-title animated fadeInDown"><%- link_to(page.path, page.title || "Untitled", {class: ""}) %>
    21|             </h3>
 >> 22|             <% if (theme.symbols_count_time.enable) {%>
    23|             <p class="post-count animated fadeInDown">
    24|                 <% if (theme.symbols_count_time.wordCount) { %>
    25|                 <span>

Cannot read property 'enable' of undefined
    at eval (E:\Projects\Blog\blog\themes\obsidian\layout\_partial\post\article.ejs:39:37)
    at article (E:\Projects\Blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (E:\Projects\Blog\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\Projects\Blog\blog\themes\obsidian\layout\post.ejs:15:17)
    at post (E:\Projects\Blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Projects\Blog\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\Projects\Blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Projects\Blog\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\Projects\Blog\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: 'E:\\Projects\\Blog\\blog\\themes\\obsidian\\layout\\post.ejs'
}
ERROR TypeError: E:\Projects\Blog\blog\themes\obsidian\layout\archive.ejs:10
    8|                 <div class="content animated fadeIn">
    9|                     <div class="set">
 >> 10|                         <h1 style="text-align: center"><%= theme.page_titles.archives || __("Archived") %></h1>
    11|                         <p style="text-align: center">「 <%= site.posts.length %> 」</p>
    12|                         <ul class="timeline timeline-centered">
    13|                             <% var posts = site.posts.sort('date', 'desc'); %>

Cannot read property 'archives' of undefined
    at eval (E:\Projects\Blog\blog\themes\obsidian\layout\archive.ejs:12:44)
    at archive (E:\Projects\Blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Projects\Blog\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\Projects\Blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Projects\Blog\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\Projects\Blog\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: 'E:\\Projects\\Blog\\blog\\themes\\obsidian\\layout\\archive.ejs'
}
ERROR TypeError: E:\Projects\Blog\blog\themes\obsidian\layout\archive.ejs:10
    8|                 <div class="content animated fadeIn">
    9|                     <div class="set">
 >> 10|                         <h1 style="text-align: center"><%= theme.page_titles.archives || __("Archived") %></h1>
    11|                         <p style="text-align: center">「 <%= site.posts.length %> 」</p>
    12|                         <ul class="timeline timeline-centered">
    13|                             <% var posts = site.posts.sort('date', 'desc'); %>

Cannot read property 'archives' of undefined
    at eval (E:\Projects\Blog\blog\themes\obsidian\layout\archive.ejs:12:44)
    at archive (E:\Projects\Blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Projects\Blog\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\Projects\Blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Projects\Blog\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\Projects\Blog\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: 'E:\\Projects\\Blog\\blog\\themes\\obsidian\\layout\\archive.ejs'
}
ERROR TypeError: E:\Projects\Blog\blog\themes\obsidian\layout\index.ejs:3
    1| <%- partial("_partial/menu", null, {cache: true}) %>
    2| <div id="container">
 >> 3|     <%- partial("_partial/screen", null, {cache: false}) %>
    4|     <div id="primary">
    5|         <%- partial('_partial/list', {start: 1}) %>
    6|     </div>

E:\Projects\Blog\blog\themes\obsidian\layout\_partial\screen.ejs:57
    55|         <h3 class="post-title animated fadeInDown">
    56|             <%- link_to(first.path, first.title || config.title, {class: "posttitle"}) %></h3>
 >> 57|         <% if (theme.symbols_count_time.enable) {%>
    58|         <p class="post-count animated fadeInDown">
    59|             <% if (theme.symbols_count_time.wordCount) { %>
    60|             <span>

Cannot read property 'enable' of undefined
    at eval (E:\Projects\Blog\blog\themes\obsidian\layout\_partial\screen.ejs:72:37)
    at screen (E:\Projects\Blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (E:\Projects\Blog\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\Projects\Blog\blog\themes\obsidian\layout\index.ejs:13:17)
    at index (E:\Projects\Blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Projects\Blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Projects\Blog\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\Projects\Blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Projects\Blog\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\Projects\Blog\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: 'E:\\Projects\\Blog\\blog\\themes\\obsidian\\layout\\index.ejs'
}
(node:2696) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2696) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:2696) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:2696) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:2696) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:2696) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency

**Comment by kcn3388** [comment]
检查主题配置文件，对着模板来写你自己的配置文件
