### ISSUE TITLE
运行hexo g错误

### ISSUE THREAD

**Issue by Yangzhijie520** [bennyxguo/hexo-theme-obsidian#182]
[error.md](https://github.com/bennyxguo/hexo-theme-obsidian/files/12327070/error.md)

**Comment by Yangzhijie520** [comment]
`PS D:\Desktop\LTFOE_Blog> hexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 105 ms
ERROR
TypeError: D:\Desktop\LTFOE_Blog\themes\obsidian\layout\post.ejs:4
    2|     <%- partial("_partial/post/header")%>
    3|     <div class="section">
 >> 4|         <%- partial("_partial/post/article")%>
    5|     </div>
    6| </div>

D:\Desktop\LTFOE_Blog\themes\obsidian\layout\_partial\post\article.ejs:22
    20|             <h3 class="post-title animated fadeInDown"><%- link_to(page.path, page.title || "Untitled", {class: ""}) %>
    21|             </h3>
 >> 22|             <% if (theme.symbols_count_time.enable) {%>
    23|             <p class="post-count animated fadeInDown">
    24|                 <% if (theme.symbols_count_time.wordCount) { %>
    25|                 <span>

Cannot read properties of undefined (reading 'enable')
    at eval ("D:\\Desktop\\LTFOE_Blog\\themes\\obsidian\\layout\\_partial\\post\\article.ejs":39:37)
    at article (D:\Desktop\LTFOE_Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval ("D:\\Desktop\\LTFOE_Blog\\themes\\obsidian\\layout\\post.ejs":15:17)
    at post (D:\Desktop\LTFOE_Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ERROR
TypeError: D:\Desktop\LTFOE_Blog\themes\obsidian\layout\archive.ejs:10
    8|                 <div class="content animated fadeIn">
    9|                     <div class="set">
 >> 10|                         <h1 style="text-align: center"><%= theme.page_titles.archives || __("Archived") %></h1>
    11|                         <p style="text-align: center">「 <%= site.posts.length %> 」</p>
    12|                         <ul class="timeline timeline-centered">
    13|                             <% var posts = site.posts.sort('date', 'desc'); %>

Cannot read properties of undefined (reading 'archives')
    at eval ("D:\\Desktop\\LTFOE_Blog\\themes\\obsidian\\layout\\archive.ejs":12:44)
    at archive (D:\Desktop\LTFOE_Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ERROR
TypeError: D:\Desktop\LTFOE_Blog\themes\obsidian\layout\archive.ejs:10
    8|                 <div class="content animated fadeIn">
    9|                     <div class="set">
 >> 10|                         <h1 style="text-align: center"><%= theme.page_titles.archives || __("Archived") %></h1>
    11|                         <p style="text-align: center">「 <%= site.posts.length %> 」</p>
    12|                         <ul class="timeline timeline-centered">
    13|                             <% var posts = site.posts.sort('date', 'desc'); %>

Cannot read properties of undefined (reading 'archives')
    at eval ("D:\\Desktop\\LTFOE_Blog\\themes\\obsidian\\layout\\archive.ejs":12:44)
    at archive (D:\Desktop\LTFOE_Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ERROR Render HTML failed: categories/index.html
TypeError: D:\Desktop\LTFOE_Blog\themes\obsidian\layout\layout.ejs:1
 >> 1| <%- partial('_partial/head') %>
    2|
    3| <body class="loading">
    4|     <div class="loader">

D:\Desktop\LTFOE_Blog\themes\obsidian\layout\_partial\head.ejs:45
    43|     <%- theme.header_html %>
    44|     <%- css(['//cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css']) %>
 >> 45|     <% if (theme.aplayer.enable == true) { %>
    46|     <script>var musiclist = "<%- theme.aplayer.musiclist%>"</script>
    47|     <%- js(['/js/loadaplayer.js'])%>
    48|     

Cannot read properties of undefined (reading 'enable')
    at eval ("D:\\Desktop\\LTFOE_Blog\\themes\\obsidian\\layout\\_partial\\head.ejs":109:26)
    at head (D:\Desktop\LTFOE_Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval ("D:\\Desktop\\LTFOE_Blog\\themes\\obsidian\\layout\\layout.ejs":10:17)
    at layout (D:\Desktop\LTFOE_Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)
ERROR
TypeError: D:\Desktop\LTFOE_Blog\themes\obsidian\layout\layout.ejs:1
 >> 1| <%- partial('_partial/head') %>
    2|
    3| <body class="loading">
    4|     <div class="loader">

D:\Desktop\LTFOE_Blog\themes\obsidian\layout\_partial\head.ejs:45
    43|     <%- theme.header_html %>
    44|     <%- css(['//cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css']) %>
 >> 45|     <% if (theme.aplayer.enable == true) { %>
    46|     <script>var musiclist = "<%- theme.aplayer.musiclist%>"</script>
    47|     <%- js(['/js/loadaplayer.js'])%>
    48|     

Cannot read properties of undefined (reading 'enable')
    at eval ("D:\\Desktop\\LTFOE_Blog\\themes\\obsidian\\layout\\_partial\\head.ejs":109:26)
    at head (D:\Desktop\LTFOE_Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval ("D:\\Desktop\\LTFOE_Blog\\themes\\obsidian\\layout\\layout.ejs":10:17)
    at layout (D:\Desktop\LTFOE_Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)
ERROR
TypeError: D:\Desktop\LTFOE_Blog\themes\obsidian\layout\index.ejs:3
    1| <%- partial("_partial/menu", null, {cache: true}) %>
    2| <div id="container">
 >> 3|     <%- partial("_partial/screen", null, {cache: false}) %>
    4|     <div id="primary">
    5|         <%- partial('_partial/list', {start: 1}) %>
    6|     </div>

D:\Desktop\LTFOE_Blog\themes\obsidian\layout\_partial\screen.ejs:57
    55|         <h3 class="post-title animated fadeInDown">
    56|             <%- link_to(first.path, first.title || config.title, {class: "posttitle"}) %></h3>
 >> 57|         <% if (theme.symbols_count_time.enable) {%>
    58|         <p class="post-count animated fadeInDown">
    59|             <% if (theme.symbols_count_time.wordCount) { %>
    60|             <span>

Cannot read properties of undefined (reading 'enable')
    at eval ("D:\\Desktop\\LTFOE_Blog\\themes\\obsidian\\layout\\_partial\\screen.ejs":72:37)
    at screen (D:\Desktop\LTFOE_Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval ("D:\\Desktop\\LTFOE_Blog\\themes\\obsidian\\layout\\index.ejs":13:17)
    at index (D:\Desktop\LTFOE_Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ERROR
TypeError: D:\Desktop\LTFOE_Blog\themes\obsidian\layout\archive.ejs:10
    8|                 <div class="content animated fadeIn">
    9|                     <div class="set">
 >> 10|                         <h1 style="text-align: center"><%= theme.page_titles.archives || __("Archived") %></h1>
    11|                         <p style="text-align: center">「 <%= site.posts.length %> 」</p>
    12|                         <ul class="timeline timeline-centered">
    13|                             <% var posts = site.posts.sort('date', 'desc'); %>

Cannot read properties of undefined (reading 'archives')
    at eval ("D:\\Desktop\\LTFOE_Blog\\themes\\obsidian\\layout\\archive.ejs":12:44)
    at archive (D:\Desktop\LTFOE_Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Desktop\LTFOE_Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Desktop\LTFOE_Blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
INFO  Generated: categories/index.html
INFO  1 files generated in 22 ms`
